feat(back-top): init back-top
ecaps1038/yike-design-dev pull request #38
Opened 2023-07-13 12:01 UTC by printfCYQ

2023-07-13 14:40 UTC, Rickon-DAFEI commented on demo/src/examples/back-top/back-top-base.vue
> +    <ul ref="list" style="height: 200px; overflow-y: auto">
请尽量避免使用行内样式

2023-07-13 18:19 UTC, Rickon-DAFEI requested changes
感谢PR！！！
经过review，目前存在的问题已经通过commits传达
欢迎在修改后再次PR！
再次感谢！！！

2023-07-13 18:19 UTC, Rickon-DAFEI commented on packages/yike-design-ui/src/components/back-top/src/back-top.vue
> +const props = defineProps({
请参照其他组件进行props定义

2023-07-13 18:19 UTC, Rickon-DAFEI commented on packages/yike-design-ui/src/components/back-top/src/back-top.vue
> +<style scoped lang="less">
请参照其他组件将样式文件抽出

2023-07-14 03:28 UTC, printfCYQ commented
根据commits 提交了新的pr

2023-07-14 03:28 UTC, closed without merging